### ISSUE TITLE
How is the value of the moons calculated?

### ISSUE THREAD

**Issue by orionshock** [chrRtg/eve-skylizer#12]
it is un-clear how the value of each moon is calculated
please explain :)

**Comment by chrRtg** [comment]
Just an example:
The moon goo has the following composition:
41% Sperrylite 5,221
21% Resplendant Kernite 163
20% Platinoid Omber 51
18% Flawless Arkonor 3,403

The last number is the price from EVE itself, some average to give us some idea on the ISK value.
The caculate (41% of 5,221) + (21% of 163) + (20% of 51) + (18% of 3403) = 2797,58

It's meant as an idicator of the ore value, not a real value itself a industrialist will use.

For the Ore-Value it's the same. The composition above will be refined (in a ideal world with 100% refining efficiency) into:
1,638 Platinum 25,485
409 Evaporite Deposits 1,789
6,608 Megacyte 587
2,047 Zydrine 533
98,902 Mexallon 70
46,127 Isogen 27
681,060 Tritanium 6
2,355 Pyerite 4
Total: 598000 ISK

The total is calculated as seen above for goo.  598000 ISK for it?

**Comment by chrRtg** [comment]
explained/done :)

**Comment by aaronmaynard** [comment]
Editing again so I can provide you with more information to help me out.
https://imgur.com/a/sYzbvZl
This moon, when running a Survey Scanner II, reads an evepraisal value of over 500 million for a 6 hour 50 minute pull.  As you can see from the image the moon survey data brings calculations to 263k.  Trying to figure out what it meant exactly we did brute force math... trying to see if that was a value per pull hour, etc etc.  But we could not figure it out.

Using Fuzzworks https://www.fuzzwork.co.uk/ore/moon.php, it gives us a per hour pull according to the scan, but we no longer have those scans.  In your post above where you explain what the numbers mean, I understand how you are getting them, but what are they in relation to? How can we calculate a week vs month pull value? 

Thank you for the assistance.

An idea.  Would it be possible to store the raw data used for these calculations in our DB so we may download the scan?  Say a download scan column that can parse the db?

**Comment by chrRtg** [comment]
The price calculation is the one above. The first critical information is the price I use for the calculation. It's the "adjusted_price" from [(ESI API market prices)](https://esi.evetech.net/latest/markets/prices/?datasource=tranquility)

For "Platinoid Omber" which is ID 46684 it shows a price of 30,9 ISK while the same at [evepraisal shows up with a Jita sell of 499 ISK](https://evepraisal.com/a/mns8u).

And I do a simple calcualtion of "what is the value of the ore in the scan". I do not take in consideration what the value of a 14 days run is, what you'll get with a reprocessing of 55.5% nor I get real Jita prices.

At the moment I simply create values which allow us to compare moons if they are worth more or less and to show the composition in detail.

But I'm open to any suggestion. If you might tell me how to calculate more usefull numbers. I'm happy to implement it.

**Comment by aaronmaynard** [comment]
The calculations are fine, it was just rather difficult how it all worked.  I am not sure why, but the second explanation seemed more insightful for me, maybe it's because I got to see a spreadsheet. 🤓 
All being said, I was able to recreate the values for both columns with pen and paper, which I think allowed me to understand more easily.  
The "amount" numbers in the Ore category in my image for example will show 22823 for Isogen. The reason why I kept scratching my head before was because I had no idea what this number meant.  In calculations this is supposed to be 22823% or a multiplier of 228.23, this is where I believe orionshock, or any other potential head scratchers were getting confused.  Might I suggest adjusting the format to include the '%' for the second section?  

Now that I know where the numbers come from I will work on ways of getting an hours/value number.  It could possible be as adding something in the "about" section... maybe "Multiply Ore-Value by X".
