### ISSUE TITLE
GuzzleHttp\Exception\RequestException after EVE_SSO Authorization

### ISSUE THREAD

**Issue by aaronmaynard** [chrRtg/eve-skylizer#15]
![Image of Error](https://i.imgur.com/wi8pIFa.png)

I was receiving an error that the callback uri did not match.  Reading through previous issue #8 I had cleared the cache.  This is what I was greeted with afterwards.

**Comment by chrRtg** [comment]
dear @aaronmaynard please do not report issues caused by the php and server your use here. I can not provide a generice computer doctor service.
Apart from that I assume you had asked your favourite search engine for "curl error 60" or similar. A first possible starting point might be https://stackoverflow.com/questions/21114371/php-curl-error-code-60

Kind regards, RtgQuack
