### ISSUE TITLE
Corp data not being completely updated.

### ISSUE THREAD

**Issue by tonytonyistony** [chrRtg/eve-skylizer#29]
The last few days Ive been trying to figure out why I cannot get any what seems to be "newer" corps to populate in the "owner" section of the tool. I have ran the following commands and they all run without error.

"/usr/bin/php ./bin/skylizer_console.php update:allycorp --ally"
"/usr/bin/php ./bin/skylizer_console.php update:allycorp --corp"
"/usr/bin/php ./bin/skylizer_console.php update:allycorp --corp --all"
I let the --all command run all night, and I did notice that it had listed hundreds of corp names, but at the end it said...
"0 Alliances and 2 corporations were updated"

When I woke up I cleared the cache, reboot the server and tried to search a corp that Ive been trying to add and still it is not populating the corporation.

I also went and tested this corporation on your public site and it also doesnt work.

The corporation in questions: "https://zkillboard.com/corporation/98583272/"

It is also not limited to just this corp. Ive tried to add numerous corporations and have yet to have the tool find a corporation I need to add.

Thanks for taking time out of your busy schedule. I really enjoy your tool.

**Comment by chrRtg** [comment]
The problem is to fetch the corporations. ESI give us a solution to get all alliances. From this starting point we can fetch all corporations in a given alliance. The problem is, how to get the corporations not affiliated? If have no solution for this yet, sorry. 
But I was thinking to allow a "deeper" search who will search ESI direct for a corp by name. That's possible.

**Comment by tonytonyistony** [comment]
A possible solution is to allow us to enter custom name of our choosing in the corp field. Right now, if it isnt in the database it doesnt allow us to fill the field at all.

**Comment by chrRtg** [comment]
solved. Try to assign a corporation to a structure. If the corporation is not found locally just add a plus sign (+) to your search term to invoke a ESI search. 
Attention, for some 3 letter terms this may take a certain ammount of time because of the huge number of results and the time neccessary to fetch each resulting corporation and to persist her to the database.
