### ISSUE TITLE
"php composer.phar install" Could not open input file: composer.phar

### ISSUE THREAD

**Issue by H4Z4RD-H42** [chrRtg/eve-skylizer#6]
Hi, i'm trying to install this beatiful tool on DigitalOcean LAMP server (ubuntu 16.04 and a manually installed PHP 7.2) but after clone the project and enter inside the folder, the command `php composer.phar install` not work for me, i always have `Could not open input file: composer.phar` error.

I google a lot and try a lot of fix, but no one work, with some of them, i have this situation: https://pastebin.com/n0hN58eG

Please can you help me to fix that?

**Comment by chrRtg** [comment]
According to the message in your pastebin your PHP installation lacks some PHP libraries. That's not an issue of skylizer but something you may solve together with your hosting company.

If the server is a "root server" and you are the server administrator you should read the pastbin because it describes the action to be taken, to install:
- PHP extension ext-intl
- PHP extension mbstring

Maybe this link may give you some furhter advice: https://tecadmin.net/enable-disable-php-modules-ubuntu/

**Comment by chrRtg** [comment]
closed cause a non skylzer issue.

**Comment by H4Z4RD-H42** [comment]
I'm sorry but maybe i not explain good my issue... This is what i do step by step:

1. go to `var/www/`
2. clone project with command `git clone https://github.com/chrRtg/eve-skylizer.git`
3. cd to `eve-skylizer` folder
4. do command `php composer.phar install` but i receive error `Could not open input file: composer.phar`
5. Tried to do command `composer install` and i receive the error in the pastebin link.
6. Tried to install requested extensions one by one and do command `php composer.phar install` everytime, but i receive always error `Could not open input file: composer.phar`

I'm not a programmer or a linux expert, but if i understand well, the command `php composer.phar install` install all the necessary, extensions included. I installed succesfully ext-intl, ext-mbstring, ext-gd and others requested extension manually but i always receive error when i do `php composer.phar install`.

Thanks for support.

_PHP 7.1.18-1+ubuntu16.04.1_

**Comment by chrRtg** [comment]
Maybe composer is not available on your server? 

IN tis case your providers documentation should help. e.g. https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-ubuntu-16-04

In this case you may have to execute composer with a different command:

```bash
composer install
```

instead of 

```bash
php composer.phar install
```

I had updated the documentation accordingly. Thank you for your valuable input.

**Comment by H4Z4RD-H42** [comment]
Nothing to do... trying by 3 hours and success to install all the necessary but the index page not show up. If i go, for example, to `http://my-domain.com/css` i see a list of files, then i reach it but somethings not work.

I stop here, thanks so much for support.

**Comment by chrRtg** [comment]
Sorry to hear that. Looks like you have to fully configure your server first, at least the apache webserver. Maybe I may help you using teamviewer or such. You may get in touch with me ingame: "Rtg Quack" if you like, discord is available too.

Fly safe

**Comment by H4Z4RD-H42** [comment]
Discord Discord! I already sent you ingame mail 2 days ago.

Just to inform that i already tried both solutions... a pre-configured stack of ubuntu (LAMP) and a empty server that i configured step by step (apache2, php and mysql) but without success. I'm definitely wrong or I forget something...

**Comment by mkerengajames** [comment]
Check your terminal location. You must be inside the Yii main folder that contains composer.phar for it to work with command

php composer,phar update

otherwise, it will say could not open input file: composer.phar
